###############################################
### CREATE SITE MASTER (DEEP INSERT ENABLED)
###############################################
POST http://localhost:4004/odata/v4/site-management/siteMaster
Content-Type: application/json

{
  "customer_name": "Steel",
  "location": "Delhi",
  "runner_id": "RUN-202",
  "campaign_no": "CMP-101",
  "repair_status": "Major",
  "minor_repair_status": 2,
  "no_of_production_line": 3,
  "siteProductionLines": [
    {
      "line_name": "Line 1",
      "no_of_spg_sensors": 4,
      "no_of_mudgun_sensors": 2,
      "sensors": [
        { "sensor_type": "SPG", "reading": 55.5,"sensor_name":"s1" },
        { "sensor_type": "MUDGUN", "reading": 41.3,"sensor_name":"s2"  }
      ]
    },
    {
      "line_name": "Line 2",
      "no_of_spg_sensors": 3,
      "no_of_mudgun_sensors": 1,
      "sensors": [
        { "sensor_type": "SPG", "reading": 60.2 }
      ]
    }
  ]
}


###############################################
### GET ALL SITE MASTERS
###############################################
GET http://localhost:4004/odata/v4/site-management/siteMaster



###############################################
### GET SITE MASTER BY ID
###############################################
GET http://localhost:4004/odata/v4/site-management/siteMaster(ID='<SiteMasterUUID>')



###############################################
### CREATE PRODUCTION LINE (NORMAL INSERT)
###############################################
POST http://localhost:4004/odata/v4/site-management/siteProductionLine
Content-Type: application/json

{
  "line_name": "Line A",
  "no_of_spg_sensors": 2,
  "no_of_mudgun_sensors": 1,
  "site_ID": "<SiteMasterUUID>"
}



###############################################
### CREATE SENSOR (NORMAL INSERT)
###############################################
POST http://localhost:4004/odata/v4/site-management/sensors
Content-Type: application/json

{
  "sensor_type": "SPG",
  "reading": 42.5,
  "line_ID": "<ProductionLineUUID>",
  "site_ID": "<SiteMasterUUID>"
}



###############################################
### GET ALL PRODUCTION LINES
###############################################
GET http://localhost:4004/odata/v4/site-management/siteProductionLine



###############################################
### GET ALL SENSORS
###############################################
GET http://localhost:4004/odata/v4/site-management/sensors



###############################################
### EXPAND: SITE MASTER → PRODUCTION LINES → SENSORS
###############################################
GET http://localhost:4004/odata/v4/site-management/siteMaster?$expand=siteProductionLines($expand=sensors)



###############################################
### EXPAND: PRODUCTION LINE → SENSORS
###############################################
GET http://localhost:4004/odata/v4/site-management/siteProductionLine?$expand=sensors



###############################################
### EXPAND EVERYTHING
###############################################
GET http://localhost:4004/odata/v4/site-management/siteMaster?$expand=*,siteProductionLines($expand=*)


###
GET http://localhost:4004/odata/v4/site-management/siteMaster('7d98f0e0-1cb0-40bf-a9ef-0e51a9fb3de7')?$expand=siteProductionLines($expand=sensors)




### Get Site with Production Lines and Sensors
GET http://localhost:4004/odata/v4/site-management/siteMaster(site_id='SITE-TRL-PUN-RUN-001')?$expand=siteProductionLines($expand=sensors,dailyProductions)
Accept: application/json


### Get Site with Lines, Sensors and DailyProduction (by date)
GET http://localhost:4004/odata/v4/site-management/siteMaster(site_id='SITE-TRL-PUN-RUN-001')?$expand=siteProductionLines($expand=sensors,dailyProductions($filter=production_date eq 2025-12-15))
Accept: application/json

### Submit Daily Production (Finalize for a site & date)
POST http://localhost:4004/odata/v4/site-management/submitDailyProduction
Content-Type: application/json
Accept: application/json

{
  "site_id": "SITE-TRL-CHE-RUN-001",
  "date": "2025-12-16"
}

###
POST http://localhost:4004/odata/v4/site-management/campaign
Content-Type: application/json

{
}
### Update Site Production Line
PATCH http://localhost:4004/odata/v4/site-management/siteProductionLine('1022e24d-934e-4718-bd2c-daa7656f1087')
Content-Type: application/json
Accept: application/json

{
  "curr_campaign": "cp3",
  "curr_repair_status": "minor",
  "curr_minor_repair_status": "1"

}

### Generate Campaign Number
GET http://localhost:4004/odata/v4/site-management/generateCampaignNumber(customer_name='TRL',location='Pune',runner_id='Blast',line_name='EAST')
Accept: application/json



